version: '3.7'
services:

  directslave:
    image: powerkernel/directslave
    ports:
      - target: 2222
        published: 2222
        protocol: tcp
      - target: 53
        published: 53
        protocol: tcp
      - target: 53
        published: 53
        protocol: udp